Feature: Example

    Background:
        Given I...

    Scenario: Example 1
        Given I...
        Then I...

    Scenario: Example 2
        Given I...
        And I...
        When I...
        Then I...