[build]
    publish = ".next"
    command = "yarn build"

[[plugins]]
    package = "netlify-plugin-cache-nextjs"

[[plugins]]
    package = "@netlify/plugin-nextjs"

[[redirects]]
    from = "/admin"
    to = "/admin/index.html"