publish_mode: editorial_workflow


backend:
  name: github
  repo: neefrehman/allergies.travel
  branch: staging # TODO: update to master after launch
  open_authoring: true # docs: https://www.netlifycms.org/docs/open-authoring/ 


media_folder: public/static/uploads
public_folder: /uploads


collections:

  - name: "allergens" # Used in routes, e.g., /admin/collections/tracks
    label: "Allergens" # Used in the UI
    folder: "src/data/allergens"
    extension: "json"
    format: "json"
    create: true
    editor:
      preview: false

    fields:
      - {label: Name, name: name, widget: string}
      - label: Translations
        name: translations
        widget: list
        required: false
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Language code, name: language_code, widget: string, hint: the three-letter ISO 639-3 code. e.g. "fra"}


  - name: "countries"
    label: "Countries"
    folder: "src/data/countries"
    extension: "json"
    format: "json"
    create: false
    editor:
      preview: false

    fields:
      - label: "Info"
        name: "info"
        widget: "object"
        collapsed: true
        summary: Basic info about the country
        fields: 
          # TODO: align with BaseCountryData schema
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Capital", name: "capital", widget: "string" }
          - { label: "Region", name: "region", widget: "string" }
          - { label: "Subregion", name: "subregion", widget: "string", required: false }
          - { label: "Languages", name: "languages", widget: "string" } # Should be list
          - { label: "Translations", name: "translations", widget: "string", required: false } # Should be list
          - { label: "Currencies", name: "currencies", widget: "string", required: false } # Should be list
          - { label: "Flag", name: "flag", widget: "string" }
          - { label: "Coordinates", name: "coordinates", widget: "string" }
          - { label: "cca2", name: "cca2", widget: "string", required: false }
          - { label: "cca3", name: "cca3", widget: "string", required: false }
          - { label: "ccn3", name: "ccn3", widget: "string", required: false }

      - name: Cuisine Description
        label: cuisine_description
        widget: object
        collapsed: false
        summary: Information about the countries cuisine
        required: false
        fields: 
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Source url", name: "source_url", widget: "string" }

      - name: Allergens
        label: allergens
        widget: list
        fields: 
          - { label: "Allergen Name", name: "allergen_name", widget: relation, collection: allergens, value_field: name, search_fields: [name] }
          - label: "Found in"
            name: "found_in"
            widget: list
            fields:
              - { label: "Food Name", name: "food", widget: string }