publish_mode: editorial_workflow

backend:
  name: github
  repo: neefrehman/allergies.travel
  branch: staging # TODO: update to master on launch
  open_authoring: true # docs: https://www.netlifycms.org/docs/open-authoring/ 

media_folder: public/static/uploads
public_folder: /uploads

i18n:
  structure: multiple_folders
  locales: ["en", "de", "es"]
  default_locale: "en"


collections:

  - name: allergens # Used in routes, e.g., /admin/collections/allergens
    label: "Allergens" # Used in the UI
    folder: "src/data/allergens"
    extension: "json"
    format: "json"
    create: true
    editor:
      preview: false

    fields:
      - { label: Name, name: name, widget: string }
      - { label: "Last Modified", name: "lastModified", widget: "hidden" }


  - name: countries
    label: "Countries"
    folder: "src/data/countries"
    extension: "json"
    format: "json"
    create: false
    i18n: true
    editor:
      preview: false

    fields:
      - { label: "Title", name: title, widget: "string", i18n: true }
      - { label: "Slug", name: slug, widget: "string", hint: "A URL-friendly version of the name. e.g. 'papua-new-guinea'", i18n: duplicate }
      - { label: "Last Modified", name: lastModified, widget: "hidden", i18n: duplicate }

      - name: allergens
        label: "Allergens"
        widget: list
        i18n: true
        fields:
          - { label: "Allergen Name", name: allergenName, widget: relation, collection: allergens, value_field: name, search_fields: [name] }
          - { label: "Slug", name: slug, widget: string, hint: "A URL-friendly version of the name. e.g. 'mutter-paneer'", i18n: duplicate  }
          - { label: "Description", name: descriptionInCuisine, widget: text, hint: "A short piece of informaiton about the use of this ingredient in the country's cuisine", required: false, i18n: true }
          - label: "Found in"
            name: "foundIn"
            widget: list
            fields:
              - { label: "Food Name", name: foodName, widget: string, i18n: true }
              - { label: "Food Description", name: description, widget: text, i18n: true }
              - { label: "Info url", name: infoUrl, widget: string, i18n: duplicate }

      - name: cuisineDescription
        label: "Cuisine Description"
        widget: object
        collapsed: false
        summary: Information about the countries cuisine
        required: false
        i18n: true
        fields:
          - { label: "Description", name: "description", widget: "text", required: false, i18n: true }
          - { label: "Source url", name: "sourceUrl", widget: "string", required: false, i18n: true }

      - name: baseInfo
        label: "Base Info"
        widget: object
        collapsed: true
        summary: Basic info about the country
        i18n: true
        fields: 
          - name: name
            label: "Name"
            widget: object
            collapsed: false
            i18n: true
            fields:
              - { label: "Common", name: common, widget: "string", i18n: true }
              - { label: "Official", name: official, widget: "string", i18n: true }
              - label: "Native"
                name: native
                widget: list
                collapsed: true
                minimize_collapsed: true
                i18n: true
                fields:
                  - { label: "Common", name: common, widget: "string", i18n: duplicate }
                  - { label: "Official", name: official, widget: "string", i18n: duplicate }
                  - { label: "ISO 639-1 code", name: languageCode, widget: string, hint: the two-letter ISO 639-1 code. e.g. "eng", i18n: duplicate }
          - { label: "Capital", name: capital, widget: "string", i18n: true }
          - { label: "Region", name: region, widget: "string", i18n: true }
          - { label: "Subregion", name: subregion, widget: "string", i18n: true }
          - { label: "Flag", name: flag, widget: "string", i18n: duplicate }
          - label: "Languages"
            name: languages
            widget: list
            i18n: true
            fields:
              - { label: "Name", name: name, widget: string, i18n: true }
              - { label: "ISO 639-1 code", name: languageCode, widget: string, hint: the two-letter ISO 639-1 code. e.g. "eng", i18n: duplicate }
          - name: currencies
            label: "Currencies"
            widget: list
            required: false
            i18n: true
            fields:
              - { label: "Name", name: name, widget: "string", i18n: true }
              - { label: "Symbol", name: symbol, widget: "string", i18n: duplicate }
              - { label: ISO 4217 currency code, name: currencyCode, widget: string, hint: the three-letter currency code. e.g. "USD", i18n: duplicate }
          - name: coordinates
            label: "Coordinates"
            widget: object
            collapsed: true
            i18n: true
            fields:
              - { label: "Latitude", name: "latitude", widget: "number", step: 0.000001, i18n: duplicate }
              - { label: "Longitude", name: "longitude", widget: "number", step: 0.000001, i18n: duplicate }
          - name: codes
            label: "Codes"
            widget: object
            collapsed: true
            required: false
            i18n: true
            fields:
              - { label: "cca2", name: "cca2", widget: "string", required: false, i18n: duplicate }
              - { label: "cca3", name: "cca3", widget: "string", required: false, i18n: duplicate }
              - { label: "ccn3", name: "ccn3", widget: "string", required: false, i18n: duplicate }