/**
 * auto-generated by scripts/generateLocalisedLocationMappings.ts
 */
export const regionNameMappings: Record<string, Record<string, string>> = {
    Americas: { en: "Americas", de: "Middle America", es: "Middle America" },
    Asia: { en: "Asia", de: "Asien", es: "Asia" },
    Africa: { en: "Africa", de: "Afrika", es: "África" },
    Europe: { en: "Europe", de: "Europa", es: "Europa" },
    Oceania: { en: "Oceania", de: "Ozeanien", es: "Oceanía" },
    Antarctic: { en: "Antarctic", de: "Antarctic, The", es: "Antarctic, The" },
};
