/**
 * auto-generated by scripts/generateLocalisedLocationMappings.ts
 */
export const regionNameMappings: Record<string, Record<string, string>> = {
  Americas: {
    en: "Americas",
    es: "Middle America",
    fr: "Middle America",
    de: "Middle America",
  },
  Asia: { en: "Asia", es: "Asia", fr: "Asie", de: "Asien" },
  Africa: { en: "Africa", es: "África", fr: "Afrique", de: "Afrika" },
  Europe: { en: "Europe", es: "Europa", fr: "Europe", de: "Europa" },
  Oceania: { en: "Oceania", es: "Oceanía", fr: "Océanie", de: "Ozeanien" },
  Antarctic: {
    en: "Antarctic",
    es: "Antarctic, The",
    fr: "Antarctic, The",
    de: "Antarctic, The",
  },
};
