/**
 * auto-generated by scripts/generateLocalisedLocationMappings.ts
 */
export const regionNameMappings: Record<string, Record<string, string>> = {
    Americas: { en: "Americas", de: "Americas", es: "Americas" },
    Asia: { en: "Asia", de: "Asia", es: "Asia" },
    Africa: { en: "Africa", de: "Africa", es: "Africa" },
    Europe: { en: "Europe", de: "Europe", es: "Europe" },
    Oceania: { en: "Oceania", de: "Oceania", es: "Oceania" },
    Antarctic: { en: "Antarctic", de: "Antarctic", es: "Antarctic" },
};
