/**
 * auto-generated by scripts/generateLocalisedLocationMappings.ts
 */
export const subregionNameMappings: Record<string, Record<string, string>> = {
    Caribbean: { en: "Caribbean", fr: "Caraïbe", de: "Karibik", es: "Caribe" },
    "Southern Asia": {
        en: "Southern Asia",
        fr: "Asie du Sud",
        de: "Südasien",
        es: "Asia del Sur",
    },
    "Middle Africa": {
        en: "Middle Africa",
        fr: "Greater Cairo Area",
        de: "Greater Cairo Area",
        es: "Greater Cairo Area",
    },
    "Northern Europe": {
        en: "Northern Europe",
        fr: "Europe du Nord",
        de: "Nordeuropa",
        es: "Europa septentrional",
    },
    "Southern Europe": {
        en: "Southern Europe",
        fr: "Europe du Sud",
        de: "Südeuropa",
        es: "Southern Europe",
    },
    "Western Asia": {
        en: "Western Asia",
        fr: "Asie de l'Ouest",
        de: "Vorderasien",
        es: "Asia Occidental",
    },
    "South America": {
        en: "South America",
        fr: "Amérique du Sud",
        de: "Südamerika",
        es: "Sudamérica",
    },
    Polynesia: {
        en: "Polynesia",
        fr: "Polynésie",
        de: "Polynesien",
        es: "Polinesia",
    },
    "": { en: "", fr: "Pamoana", de: "Pamoana", es: "Pamoana" },
    "Australia and New Zealand": {
        en: "Australia and New Zealand",
        fr: "l'Australie et la Nouvelle-Zélande",
        de: "Australien und Neuseeland",
        es: "Austral Andes Nev Zelanda",
    },
    "Western Europe": {
        en: "Western Europe",
        fr: "Europe de l'Ouest",
        de: "Westeuropa",
        es: "Europa Occidental",
    },
    "Eastern Africa": {
        en: "Eastern Africa",
        fr: "Afrique de l'Est",
        de: "Ostafrika",
        es: "África Oriental",
    },
    "Western Africa": {
        en: "Western Africa",
        fr: "Afrique de l'Ouest",
        de: "Westafrika",
        es: "África Occidental",
    },
    "Eastern Europe": {
        en: "Eastern Europe",
        fr: "Europe de l'Est",
        de: "Eastern Europe",
        es: "Europa Oriental",
    },
    "Central America": {
        en: "Central America",
        fr: "Amérique centrale",
        de: "Zentralamerika",
        es: "América Central",
    },
    "North America": {
        en: "North America",
        fr: "Amérique du Nord",
        de: "Nordamerika",
        es: "Norteamérica",
    },
    "South-Eastern Asia": {
        en: "South-Eastern Asia",
        fr: "Asie du Sud-Est",
        de: "Südostasien",
        es: "Sudeste Asiático",
    },
    "Southern Africa": {
        en: "Southern Africa",
        fr: "Afrique australe",
        de: "Südliches Afrika",
        es: "África austral",
    },
    "Eastern Asia": {
        en: "Eastern Asia",
        fr: "Asie de l'Est",
        de: "Ostasien",
        es: "Asia Oriental",
    },
    "Northern Africa": {
        en: "Northern Africa",
        fr: "Afrique du Nord",
        de: "Nordafrika",
        es: "África del Norte",
    },
    Melanesia: {
        en: "Melanesia",
        fr: "Melanesia",
        de: "Melanesia",
        es: "Melanesia",
    },
    Micronesia: {
        en: "Micronesia",
        fr: "Micronésie",
        de: "Mikronesien",
        es: "Micronesia",
    },
    "Central Asia": {
        en: "Central Asia",
        fr: "Asie centrale",
        de: "Zentralasien",
        es: "Asia Central",
    },
    "Central Europe": {
        en: "Central Europe",
        fr: "Central",
        de: "Central",
        es: "Central",
    },
};
