/**
 * auto-generated by scripts/generateLocalisedLocationMappings.ts
 */
export const subregionNameMappings: Record<string, Record<string, string>> = {
    Caribbean: { en: "Caribbean", de: "Caribbean", es: "Caribbean" },
    "Southern Asia": {
        en: "Southern Asia",
        de: "Southern Asia",
        es: "Southern Asia",
    },
    "Middle Africa": {
        en: "Middle Africa",
        de: "Middle Africa",
        es: "Middle Africa",
    },
    "Northern Europe": {
        en: "Northern Europe",
        de: "Northern Europe",
        es: "Northern Europe",
    },
    "Southern Europe": {
        en: "Southern Europe",
        de: "Southern Europe",
        es: "Southern Europe",
    },
    "Western Asia": {
        en: "Western Asia",
        de: "Western Asia",
        es: "Western Asia",
    },
    "South America": {
        en: "South America",
        de: "South America",
        es: "South America",
    },
    Polynesia: { en: "Polynesia", de: "Polynesia", es: "Polynesia" },
    "": { en: "", de: "", es: "" },
    "Australia and New Zealand": {
        en: "Australia and New Zealand",
        de: "Australia and New Zealand",
        es: "Australia and New Zealand",
    },
    "Western Europe": {
        en: "Western Europe",
        de: "Western Europe",
        es: "Western Europe",
    },
    "Eastern Africa": {
        en: "Eastern Africa",
        de: "Eastern Africa",
        es: "Eastern Africa",
    },
    "Western Africa": {
        en: "Western Africa",
        de: "Western Africa",
        es: "Western Africa",
    },
    "Eastern Europe": {
        en: "Eastern Europe",
        de: "Eastern Europe",
        es: "Eastern Europe",
    },
    "Central America": {
        en: "Central America",
        de: "Central America",
        es: "Central America",
    },
    "North America": {
        en: "North America",
        de: "North America",
        es: "North America",
    },
    "South-Eastern Asia": {
        en: "South-Eastern Asia",
        de: "South-Eastern Asia",
        es: "South-Eastern Asia",
    },
    "Southern Africa": {
        en: "Southern Africa",
        de: "Southern Africa",
        es: "Southern Africa",
    },
    "Eastern Asia": {
        en: "Eastern Asia",
        de: "Eastern Asia",
        es: "Eastern Asia",
    },
    "Northern Africa": {
        en: "Northern Africa",
        de: "Northern Africa",
        es: "Northern Africa",
    },
    Melanesia: { en: "Melanesia", de: "Melanesia", es: "Melanesia" },
    Micronesia: { en: "Micronesia", de: "Micronesia", es: "Micronesia" },
    "Central Asia": {
        en: "Central Asia",
        de: "Central Asia",
        es: "Central Asia",
    },
    "Central Europe": {
        en: "Central Europe",
        de: "Central Europe",
        es: "Central Europe",
    },
};
